repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.3.2
    hooks:
      - id: ruff # Run the linter.
        name: Run Linter Check (Ruff)
        types_or: [ python, pyi, jupyter ]
        args: [ --fix ]
        files: ^(src|tests|examples)/
      - id: ruff-format # Run the formatter.
        name: Run Formatter (Ruff)
        types_or: [ python, pyi, jupyter ]
        files: ^(src|tests|examples)/
  - repo: local
    # https://jaredkhan.com/blog/mypy-pre-commit
    hooks:
      - id: mypy
        name: mypy
        entry: "./scripts/run_mypy.sh"
        language: system
        # use your preferred Python version
        # trigger for commits changing Python files
        types: [python]
        # use require_serial so that script
        # is only called once per commit
        require_serial: true
        # print the number of files as a sanity-check
        verbose: true
