name: "🐛 Bug Report"
description: "Report an issue with APPL."
title: "Bug: [Short description of the bug]"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Please provide as much information as possible to help us diagnose the problem.

  - type: input
    id: summary
    attributes:
      label: "Summary"
      description: "A concise summary of the bug."

  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "A detailed description of the bug and how it behaves."

  - type: input
    id: version
    attributes:
      label: "APPL Version"
      description: "The version of APPL where the bug was found. Additional, please specify how you installed APPL."

  - type: input
    id: python_version
    attributes:
      label: "Python Version"
      description: "The version of Python you are using."

  - type: textarea
    id: steps
    attributes:
      label: "Steps to Reproduce"
      description: "Steps to reproduce the issue."

  - type: textarea
    id: expected_behavior
    attributes:
      label: "Expected Behavior"
      description: "What you expected to happen."

  - type: textarea
    id: actual_behavior
    attributes:
      label: "Actual Behavior"
      description: "What actually happened."

  - type: textarea
    id: additional_info
    attributes:
      label: "Additional Information"
      description: "Any additional information that may help resolve the issue."
