
name: "🚀 New Feature Request"
description: "Propose a new feature for the APPL project."
title: "Feature Request: [Your Feature Title Here]"
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature for APPL! Please provide as much information as possible to help us understand your request.

  - type: input
    id: title
    attributes:
      label: "Feature Title"
      description: "Provide a short title for your proposed feature."

  - type: textarea
    id: motivation
    attributes:
      label: "Motivation"
      description: "Explain why this feature is necessary or beneficial to the project."

  - type: textarea
    id: description
    attributes:
      label: "Feature Description"
      description: "Describe the feature and how it would work in APPL."

  - type: textarea
    id: impact
    attributes:
      label: "Potential Impact"
      description: "Describe the expected impact of the feature on the existing codebase."
